### ISSUE TITLE
token.json file error in node server

### ISSUE THREAD

**Issue by KSuondProject** [gregtbrown/whatsPlaying#2]
Hi,

I've tried to build up your project but there's a problem when I start the node server:

```
rock@xxx:~/whatsPlaying/server$ node server.js
Error reading file "/home/rock/whatsPlaying/server/data/token.json"
ENOENT: no such file or directory, open '/home/rock/whatsPlaying/server/data/token.json'
```

Seems to miss some token file in a folder that doesn't exist. 
I've create the folder "data" and put there a "token.json" file but it doesn't change:

`rock@xxx:~/whatsPlaying/server$ node server.js
Error reading file "/home/rock/whatsPlaying/server/data/token.json"
Unexpected end of JSON input`

How I can resolve it?

Thanks!

**Comment by gregtbrown** [comment]
Hi,
The token file is created dynamically at runtime to hold the spotify access token.

I'm guessing the 'data' folder is missing.  It is not specifically part of the github project and I am not explicitly creating it in the server code.  Please try creating the folder manually, but do NOT manually create the token file.  If that works for you, please let me know and I will correct the code.

Thanks for your feedback.

**Comment by KSuondProject** [comment]
Hi,
I've create the folder "data" and not the token files but it doesn't works:
`Error reading file "/home/rock/whatsPlaying/server/data/token.json"
ENOENT: no such file or directory, open '/home/rock/whatsPlaying/server/data/token.json'`
Thanks,

**Comment by KSuondProject** [comment]
Hi,
I've create the folder "data" and not the token files but it doesn't works:
`Error reading file "/home/rock/whatsPlaying/server/data/token.json"
ENOENT: no such file or directory, open '/home/rock/whatsPlaying/server/data/token.json'`
Thanks,

**Comment by gregtbrown** [comment]
I have pushed a code change which should fix your issue.
The "Error reading file" was not actually an error, but I have silenced it anyway.
However, it was also not correctly writing the token file if the folder was missing, so that is corrected now.
