### ISSUE TITLE
Can't show anybody's stats except my own

### ISSUE THREAD

**Issue by drdude684** [gregtbrown/whatsPlaying#3]
Hi, great work here and I have forked it as I have a slightly different usage scenario (adding a 'now playing' screen to a screenless player, with multiple people able to play music at that player). As it stands now, I can't show playing stats for anybody else than me. I get a 403 error from spotify. I have tried clearing the token.json file, and of course logging in and out of spotify itself as well as of the server's page, all to no avail. For myself, it works just fine. I am starting to think it has to do with the developer api being active and aware of this app.

I hate to ask, but do you have any suggestions?

**Comment by drdude684** [comment]
Aahhhh, found it! Other users have to be explicitly added to the developer dashboard, in user management. That did the trick. Sorry to have bothered you, of course this can be closed.

**Comment by gregtbrown** [comment]
Glad you figured it out!  I'm interested in your concept, please feel free to post a link to your code.

**Comment by drdude684** [comment]
Will do. It’s a voyage of discovery to me, rather new to js, html, css, git, and github. I wasn’t able to make it work by changing adaptingyour server code, but ended up with a working solution using one server for each potential user. Perhaps not the most elegant, but with the great advantage that it will work with any instance of your server (and can combine multiples of those). I want to polish a bit and I’ll make it available then.

**Comment by gregtbrown** [comment]
Just a note, perhaps for anyone else reading this, that this app will support multiple users, but currently just one at a time.  One user logs out and then another user can log in

**Comment by drdude684** [comment]
I have tried to add you to my fork. I hope that makes it possible for you to tag along with what I am doing.
